/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module CPU_SM_inputs (
  input A1,
  input BGRANT_,
  input BOEQ3,
  input CYCLEDONE,
  input DMADIR,
  input DMAENA,
  input DREQ_,
  input DSACK0_,
  input DSACK1_,
  input FIFOEMPTY,
  input FIFOFULL,
  input FLUSHFIFO,
  input LASTWORD,
  input cpudff1_q,
  input cpudff2_q,
  input cpudff3_q,
  input cpudff4_q,
  input cpudff5_q,
  output E0,
  output E1,
  output E2,
  output E3,
  output E4,
  output E5,
  output E6_d,
  output E7,
  output E8,
  output E9_d,
  output E10,
  output E11,
  output E12,
  output E13,
  output E14,
  output E15,
  output E16,
  output E17,
  output E18,
  output E19,
  output E20_d,
  output E21,
  output E22,
  output E23_sd,
  output E24_sd,
  output E25_d,
  output E26,
  output E27,
  output E28_d,
  output E29_sd,
  output E30_d,
  output E31,
  output E32,
  output E33_sd_E38_s,
  output E34,
  output E35,
  output E36_s_E47_s,
  output E37_s_E44_s,
  output E39_s,
  output E40_s_E41_s,
  output E42_s,
  output E43_s_E49_sd,
  output E45,
  output E46_s_E59_s,
  output E48,
  output E50_d_E52_d,
  output E51_s_E54_sd,
  output E53,
  output E55,
  output E56,
  output E57_s,
  output E58,
  output E60,
  output E61,
  output E62
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  assign E21 = ~ (~ (BOEQ3 & FIFOEMPTY & LASTWORD) | cpudff2_q | ~ (cpudff3_q & cpudff4_q & cpudff5_q));
  assign E35 = (cpudff2_q & cpudff3_q & cpudff4_q & cpudff5_q);
  assign s9 = ~ A1;
  assign s10 = ~ BGRANT_;
  assign s13 = ~ CYCLEDONE;
  assign s7 = ~ DMADIR;
  assign s11 = ~ DSACK0_;
  assign s12 = ~ DSACK1_;
  assign s8 = ~ FIFOEMPTY;
  assign s0 = ~ FIFOFULL;
  assign s1 = ~ LASTWORD;
  assign s3 = ~ cpudff1_q;
  assign s4 = ~ cpudff2_q;
  assign s2 = ~ cpudff3_q;
  assign s5 = ~ cpudff4_q;
  assign s6 = ~ cpudff5_q;
  assign E0 = ~ (~ (DMADIR & FIFOEMPTY & s0 & FLUSHFIFO) | ~ (DMAENA & s1 & s2 & 1'b1) | ~ (s3 & s4 & s5 & s6));
  assign E1 = (s7 & DMAENA & ~ DREQ_ & FIFOEMPTY & s3 & s4 & s5 & cpudff5_q);
  assign E2 = ~ (~ (DMADIR & DMAENA & s8 & FLUSHFIFO) | ~ (s3 & s4 & s5 & cpudff5_q) | cpudff3_q);
  assign E3 = ~ (~ (DMADIR & DMAENA & FLUSHFIFO & LASTWORD) | (s3 & s4 & s5 & cpudff5_q) | cpudff3_q);
  assign E4 = ~ (~ (s9 & s10 & CYCLEDONE & LASTWORD) | ~ (~ BOEQ3 & s3 & s2 & s6) | ~ (s4 & cpudff4_q));
  assign E5 = ~ (~ (s9 & s10 & CYCLEDONE & LASTWORD) | ~ (BOEQ3 & s3 & s2 & s6) | ~ (s4 & cpudff4_q));
  assign E6_d = (s11 & s12 & cpudff1_q & cpudff2_q & s2 & cpudff4_q & cpudff5_q);
  assign E7 = (DMADIR & DMAENA & FIFOFULL & s3 & s4 & s2 & s5 & s6);
  assign E8 = ~ (~ (s9 & s10 & CYCLEDONE & s2) | LASTWORD | ~ (s3 & s4 & cpudff4_q & s6));
  assign E9_d = (s11 & s12 & cpudff1_q & s2 & s5 & s6);
  assign E10 = (A1 & s10 & CYCLEDONE & s3 & s4 & s2 & cpudff4_q & s6);
  assign E11 = (s9 & s10 & CYCLEDONE & s3 & cpudff2_q & s2 & s5 & s6);
  assign E12 = (A1 & s10 & CYCLEDONE & s3 & cpudff2_q & s2 & s5 & s6);
  assign E13 = (s7 & DMAENA & s3 & s4 & s5 & s6);
  assign E14 = (s7 & DREQ_ & s3 & s5 & cpudff5_q);
  assign E15 = ~ (DMADIR | FIFOEMPTY | ~ (s3 & s5 & cpudff5_q));
  assign E16 = (BGRANT_ & s3 & cpudff2_q & s2 & s5 & s6);
  assign E17 = (s13 & s3 & cpudff2_q & s2 & s5 & s6);
  assign E18 = (BGRANT_ & s3 & s4 & s2 & cpudff4_q & s6);
  assign E19 = (s13 & s3 & s4 & s2 & cpudff4_q & s6);
  assign E20_d = (s12 & cpudff1_q & s4 & s2 & s5 & s6);
  assign E22 = (~ DMAENA & s3 & s5 & cpudff5_q);
  assign E23_sd = (DSACK0_ & s12 & cpudff2_q & cpudff3_q & cpudff4_q & s6);
  assign E24_sd = ~ (~ (cpudff1_q & s4 & s2) | cpudff4_q | cpudff5_q);
  assign E25_d = (s11 & s12 & cpudff2_q & cpudff3_q & cpudff4_q & s6);
  assign E26 = ~ (BOEQ3 | ~ (FIFOEMPTY & LASTWORD & s4) | ~ (cpudff3_q & cpudff4_q & cpudff5_q));
  assign E27 = (FIFOEMPTY & s1 & s4 & cpudff3_q & cpudff4_q & cpudff5_q);
  assign E28_d = (s12 & cpudff1_q & cpudff2_q & cpudff3_q & s5 & s6);
  assign E29_sd = (cpudff1_q & cpudff2_q & s2 & s5 & s6);
  assign E30_d = (s12 & cpudff1_q & cpudff2_q & s2 & s5 & s6);
  assign E31 = (s12 & cpudff1_q & s2 & cpudff4_q & cpudff5_q);
  assign E32 = (FIFOFULL & cpudff1_q & cpudff2_q & s2 & cpudff4_q & s6);
  assign E33_sd_E38_s = (cpudff1_q & cpudff2_q & cpudff3_q & s5 & s6);
  assign E34 = (s8 & s4 & cpudff3_q & cpudff4_q & cpudff5_q);
  assign E36_s_E47_s = (cpudff1_q & cpudff2_q & s2 & s5 & cpudff5_q);
  assign E37_s_E44_s = (s4 & cpudff3_q & cpudff4_q & s6);
  assign E39_s = (cpudff1_q & s4 & s2 & s5 & s6);
  assign E40_s_E41_s = (cpudff1_q & s4 & s2 & s5 & cpudff5_q);
  assign E42_s = (cpudff1_q & cpudff2_q & s2 & s5 & s6);
  assign E43_s_E49_sd = (cpudff1_q & s2 & cpudff4_q & cpudff5_q);
  assign E45 = (s3 & s4 & s2 & cpudff4_q & cpudff5_q);
  assign E46_s_E59_s = (cpudff1_q & s4 & cpudff3_q & cpudff5_q);
  assign E48 = (s0 & cpudff1_q & cpudff2_q & s2 & cpudff4_q & s6);
  assign E50_d_E52_d = (cpudff1_q & s4 & cpudff3_q & s6);
  assign E51_s_E54_sd = (cpudff2_q & cpudff3_q & cpudff4_q & s6);
  assign E53 = (s3 & s4 & cpudff3_q & s5 & s6);
  assign E55 = (s3 & cpudff2_q & cpudff3_q);
  assign E56 = (s3 & cpudff2_q & cpudff4_q & cpudff5_q);
  assign E57_s = (cpudff1_q & s4 & cpudff4_q & cpudff5_q);
  assign E58 = (s3 & cpudff3_q & s5 & cpudff5_q);
  assign E60 = (s3 & cpudff2_q & s5 & cpudff5_q);
  assign E61 = (s3 & cpudff2_q & cpudff4_q & s6);
  assign E62 = (cpudff1_q & s4 & cpudff4_q & s6);
endmodule
