name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["mbtaylor1982/ReSDMAC"]
assignees:
  - mbtaylor1982
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What firmware version are you running?
      options:
        - v0.9
        - v0.8
        - v0.7
        - v0.6
        - v0.5
        - v0.4
        - v0.3
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Machine
    attributes:
      label: What machines are you seeing the problem on?
      multiple: true
      options:
        - A3000D
        - A3000T
        - AA3000+
        - ReAmiga A3000
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mbtaylor1982/ReSDMAC/blob/v0.9/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true