name: build

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
defaults:
  run:
    working-directory: Quartus

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container:
      image: mbtaylor1982/quartus:22.1
      credentials:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PWD }}
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # 2 - RTL synthesis 10M16
      - name: Run compilation flow
        run: quartus_sh -t  RESDMAC.tcl 10M16SCU169C8G
      # 3 - Upload artifacts
      - name: Upload 10M16SCU169C8G Firmware
        uses: actions/upload-artifact@v3
        with:
          name: OutputFiles_10M16SCU169C8G.zip
          path: output_files_10M16SCU169C8G/
          retention-days: 14
      # 4 - RTL synthesis 10M16
      - name: Run compilation flow
        run: quartus_sh -t  RESDMAC.tcl 10M04SCU169C8G
      # 5 - Upload artifacts
      - name: Upload 10M04SCU169C8G Firmware
        uses: actions/upload-artifact@v3
        with:
          name: OutputFiles_10M04SCU169C8G.zip
          path: output_files_10M04SCU169C8G/
          retention-days: 14
     
