name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: raetro/quartus:13.0sp1
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2 - RTL synthesis
      - name: Run compilation flow
        run: quartus_sh --flow compile Quartus/RESDMAC.qpf
      # 3 - Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OutputFiles.zip
          path: Quartus/output_files/
          retention-days: 14