name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mbtaylor1982/quartus:22.1
      credentials:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PWD }}
    env:
      VERSION: ${{ startsWith(github.ref_name, 'v') && github.ref_name || 'v9.9'}}
    steps:
      - name: Install gencrc
        uses: robinraju/release-downloader@v1
        with:
            repository: 'mbtaylor1982/gencrc'
            latest: true
            out-file-path: '/usr/local/bin'
            fileName: 'gencrc'
      - name: add +x permission to gencrc
        run: chmod +x /usr/local/bin/gencrc
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2 - RTL synthesis 10M16
      - name: Run compilation flow 10M16
        working-directory: Quartus
        run: quartus_sh -t  RESDMAC.tcl -device 10M16SCU169C8G -version $VERSION
      - name: calcualte 10M16 checksums
        run: |
          sha256sum Quartus/output_files_10M16SCU169C8G/RESDMAC.pof > Quartus/output_files_10M16SCU169C8G/RESDMAC.pof.sha256
          gencrc Quartus/output_files_10M16SCU169C8G/resdmac_cfm0_auto.rpd > Quartus/output_files_10M16SCU169C8G/resdmac_cfm0_auto.crc32
      # 3 - Upload artifacts
      - name: Upload 10M16SCU169C8G Firmware
        uses: actions/upload-artifact@v4
        with:
          name: OutputFiles_10M16_${{ env.VERSION }}.zip
          path: Quartus/output_files_10M16SCU169C8G
          retention-days: 14
      # 4 - RTL synthesis 10M04
      - name: Run compilation flow 10M04
        working-directory: Quartus
        run: quartus_sh -t  RESDMAC.tcl -device 10M04SCU169C8G -version $VERSION
      - name: calcualte 10M04 checksums
        run: |
          sha256sum Quartus/output_files_10M04SCU169C8G/RESDMAC.pof > Quartus/output_files_10M04SCU169C8G/RESDMAC.pof.sha256
          gencrc Quartus/output_files_10M04SCU169C8G/resdmac_cfm0_auto.rpd > Quartus/output_files_10M04SCU169C8G/resdmac_cfm0_auto.crc32
        # 5 - Upload artifacts
      - name: Upload 10M04SCU169C8G Firmware
        uses: actions/upload-artifact@v4
        with:
          name: OutputFiles_10M04_${{ env.VERSION }}.zip
          path: Quartus/output_files_10M04SCU169C8G
          retention-days: 14
      # 6 - RTL synthesis 10M02
      - name: Run compilation flow 10M02
        working-directory: Quartus
        run: quartus_sh -t  RESDMAC.tcl -device 10M02SCU169C8G -version $VERSION
      - name: calcualte 10M02 checksums
        run: sha256sum Quartus/output_files_10M04SCU169C8G/RESDMAC.pof > Quartus/output_files_10M04SCU169C8G/RESDMAC.pof.sha256
      # 7 - Upload artifacts
      - name: Upload 10M02SCU169C8G Firmware
        uses: actions/upload-artifact@v4
        with:
          name: OutputFiles_10M02_${{ env.VERSION }}.zip
          path: Quartus/output_files_10M02SCU169C8G
          retention-days: 14
