name: build

#env:
#  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      version:
        description: Version Tag (eg v1.0)
        required: true
        type: string
        description: Version Tag (eg v1.0)
        default: v9.9
      use_version:
        description: Use the version tag from the input.
        default: false
        type: boolean
  workflow_call:
    inputs:
      version:
        description: Version Tag (eg v1.0)
        required: true
        type: string
        default: v9.9
      use_version:
        description: Use the version tag from the input.
        default: true
        type: boolean
defaults:
  run:
    working-directory: Quartus

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mbtaylor1982/quartus:22.1
      credentials:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PWD }}
    env:
      VERSION: ${{ inputs.use_version == true && inputs.version || 'v9.9' }}
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2 - RTL synthesis 10M16
      - name: Run compilation flow 10M16
        run: quartus_sh -t  RESDMAC.tcl -device 10M16SCU169C8G -version $VERSION
      # 3 - Upload artifacts
      - name: Upload 10M16SCU169C8G Firmware
        uses: actions/upload-artifact@v4
        with:
          name: OutputFiles_10M16SCU169C8G.zip
          path: Quartus/output_files_10M16SCU169C8G
          retention-days: 14
      # 4 - RTL synthesis 10M04
      - name: Run compilation flow 10M04
        run: quartus_sh -t  RESDMAC.tcl -device 10M04SCU169C8G -version $VERSION
      # 5 - Upload artifacts
      - name: Upload 10M04SCU169C8G Firmware
        uses: actions/upload-artifact@v4
        with:
          name: OutputFiles_10M04SCU169C8G.zip
          path: Quartus/output_files_10M04SCU169C8G
          retention-days: 14
      # 6 - RTL synthesis 10M02
      - name: Run compilation flow 10M02
        run: quartus_sh -t  RESDMAC.tcl -device 10M02SCU169C8G -version $VERSION
      # 7 - Upload artifacts
      - name: Upload 10M02SCU169C8G Firmware
        uses: actions/upload-artifact@v4
        with:
          name: OutputFiles_10M02SCU169C8G.zip
          path: Quartus/output_files_10M02SCU169C8G
          retention-days: 14
