name: make_adf

on:
    workflow_call:
jobs:
    make_update_adf:
        runs-on: ubuntu-latest
        container: walkero/amitoolsondocker:latest
        env:
          ADF_LABEL: ReSDMAC_Utils_${{ github.ref_name }}
          ADF_FILE: ReSDMAC_Utils_${{ github.ref_name }}.adf
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: download artifacts
            uses: actions/download-artifact@v4

          - name: download_resdmac_update_release
            uses: robinraju/release-downloader@v1
            with:
                repository: 'mbtaylor1982/ReSDMAC_Update_Tool'
                latest: true
                extract: true
                out-file-path: 'ReSDMAC_Update_Tool'
                fileName: 'ReSDMAC.zip'
                token: ${{ secrets.RESDMAC_UPDATE_REPO}}

          #- name: download_sdmac_release
          #  uses: robinraju/release-downloader@v1
          #  with:
          #      repository: 'cdhooper/amiga_sdmac_test'
          #      latest: true
          #      extract: true
          #      out-file-path: 'release-downloads'
          #      fileName: 'sdmac*.zip'

          #- name: download_devtest_release
          #  uses: robinraju/release-downloader@v1
          #  with:
          #      repository: 'cdhooper/amiga_devtest'
          #      latest: true
          #      out-file-path: 'release-downloads'
          #      fileName: 'devtest*.lha' #change to zip file later

          - name: Display structure of files
            run: ls -R

          - name: make_adf
            run: |
              mkdir -p ADF
              xdftool ./ADF/${{ env.ADF_FILE }} format "${{ env.ADF_LABEL }}"
              xdftool ./ADF/${{ env.ADF_FILE }} makedir C
              xdftool ./ADF/${{ env.ADF_FILE }} makedir S
              xdftool ./ADF/${{ env.ADF_FILE }} makedir Devs
              xdftool ./ADF/${{ env.ADF_FILE }} write ./ReSDMAC_Update_Tool/resdmac C/resdmac
              xdftool ./ADF/${{ env.ADF_FILE }} write ./OutputFiles_10M16SCU169C8G_${{ github.ref_name }}.zip/resdmac_cfm0_auto.rpd 10M16_update.rpd
              xdftool ./ADF/${{ env.ADF_FILE }} write ./OutputFiles_10M04SCU169C8G_${{ github.ref_name }}.zip/resdmac_cfm0_auto.rpd 10M04_update.rpd
              xdftool ./ADF/${{ env.ADF_FILE }} write ./OutputFiles_10M16SCU169C8G_${{ github.ref_name }}.zip/resdmac_cfm0_auto_crc32.txt 10M16_update.rpd.crc32
              xdftool ./ADF/${{ env.ADF_FILE }} write ./OutputFiles_10M04SCU169C8G_${{ github.ref_name }}.zip/resdmac_cfm0_auto_crc32.txt 10M04_update.rpd.crc32
              xdftool ./ADF/${{ env.ADF_FILE }} write ./disk/Startup-Sequence S/Startup-Sequence
              xdftool ./ADF/${{ env.ADF_FILE }} write ./disk/system-configuration Devs/system-configuration
              xdftool ./ADF/${{ env.ADF_FILE }} write ./disk/Disk.info
              xdftool ./ADF/${{ env.ADF_FILE }} boot install
          - name: Upload ADF file
            uses: actions/upload-artifact@v4
            with:
              name: ${{ env.ADF_FILE }}
              path: ./ADF/${{ env.ADF_FILE }}
              retention-days: 14
