name: Create New Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Trigger only when tag matches v*, i.e. v1.0, v21.12.31, v211231
jobs:
  kicad_outputs:
    uses: ./.github/workflows/kicad.yml
  build_firmware:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  create_release:
    needs: [kicad_outputs, build_firmware, test]
    runs-on: ubuntu-latest

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Copy, tag with version and create SHA256 checksum
        run: |
          mkdir -p releases
          mv ./KiCad_Outputs.zip ./KiCad_Outputs
          zip -r ./releases/KiCad_Outputs_${{ github.ref_name }}.zip ./KiCad_Outputs 
          cp OutputFiles_10M16_${{ github.ref_name }}.zip/RESDMAC.pof ./releases/RESDMAC_10M16_${{ github.ref_name }}.pof
          cp OutputFiles_10M04_${{ github.ref_name }}.zip/RESDMAC.pof ./releases/RESDMAC_10M04_${{ github.ref_name }}.pof
          cp OutputFiles_10M02_${{ github.ref_name }}.zip/RESDMAC.pof ./releases/RESDMAC_10M02_${{ github.ref_name }}.pof
          cp OutputFiles_10M16_${{ github.ref_name }}.zip/resdmac_cfm0_auto.rpd ./releases/RESDMAC_10M16_${{ github.ref_name }}.rpd
          cp OutputFiles_10M04_${{ github.ref_name }}.zip/resdmac_cfm0_auto.rpd ./releases/RESDMAC_10M04_${{ github.ref_name }}.rpd
          cp OutputFiles_10M02_${{ github.ref_name }}.zip/resdmac_cfm0_auto.rpd ./releases/RESDMAC_10M02_${{ github.ref_name }}.rpd
          sha256sum OutputFiles_10M16_${{ github.ref_name }}.zip/RESDMAC.pof > ./releases/RESDMAC_10M16_${{ github.ref_name }}.pof.sha256
          sha256sum OutputFiles_10M04_${{ github.ref_name }}.zip/RESDMAC.pof > ./releases/RESDMAC_10M04_${{ github.ref_name }}.pof.sha256
          sha256sum OutputFiles_10M02_${{ github.ref_name }}.zip/RESDMAC.pof > ./releases/RESDMAC_10M02_${{ github.ref_name }}.pof.sha256
      
      - name: Display structure of files
        run: ls -R

      - name: Create a new GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: |
            ./releases/KiCad_Outputs_${{ github.ref_name }}  
            ./releases/RESDMAC_10M16_${{ github.ref_name }}.pof
            ./releases/RESDMAC_10M04_${{ github.ref_name }}.pof
            ./releases/RESDMAC_10M02_${{ github.ref_name }}.pof
            ./releases/RESDMAC_10M16_${{ github.ref_name }}.rpd
            ./releases/RESDMAC_10M04_${{ github.ref_name }}.rpd
            ./releases/RESDMAC_10M02_${{ github.ref_name }}.rpd
            ./releases/RESDMAC_10M16_${{ github.ref_name }}.pof.sha256
            ./releases/RESDMAC_10M04_${{ github.ref_name }}.pof.sha256
            ./releases/RESDMAC_10M02_${{ github.ref_name }}.pof.sha256
            
