name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    container: hdlc/iverilog:latest
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # 2 - Run TestBench 
      - name: Run testbench
        run: |
            iverilog   -o RTL/RESDMAC_DMA_SCSI_READ_CYCLE_tb.v.out RTL/TestBench/RESDMAC_DMA_SCSI_READ_CYCLE_tb.v 
            vvp RTL/RESDMAC_DMA_SCSI_READ_CYCLE_tb.v.out 
    