name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    container: mbtaylor1982/cocotb-iverilog:latest
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # 2 - Change to cocotb test dtirectory 
      - name: Change to cocotb test dtirectory 
        run: cd /RTL/cocotb
      - name: run pytest
        uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          verbose: false
          job-summary: true

