name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    container: mbtaylor1982/cocotb-iverilog:latest
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # 2 - Run TestBench 
      - name: Run testbench
        run: make