name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  testing:
    runs-on: ubuntu-latest
    container: mbtaylor1982/cocotb-iverilog:latest
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2 - Copy files to the test directory 
      - name: Copy files
        working-directory: ${{ env.WORK_DIR }}/test
        run: cp -r .github "$GITHUB_WORKSPACE/"   
      # 3 - Change to cocotb test dtirectory 
      - name: Change to cocotb test dtirectory 
        run: cd /test/RTL/cocotb
      # 4 - Run cocotb tests using pytest
      - name: run pytest -o log_cli=true
        uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: true
          job-summary: true
          click-to-expand: false
      # 5 Upload VCD Files
      - name: upload vcd files
        uses: actions/upload-artifact@v4
        with:
          name: vcd-files
          path: sim_build/*.vcd
          retention-days: 14


